name: Install Dependencies
description: Use node and install the project dependencies
inputs:
  NX_CLOUD_ACCESS_TOKEN:
    required: true
    description: 'Nx Cloud access token'

runs:
  using: 'composite'
  steps:
    - name: ⎔ Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.14.0'
        cache: 'yarn'
    - name: ⎔ Set yarn version
      shell: bash
      run: yarn set version 1.22.19
    - name: 📥 Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
    # - name: Add NX_CLOUD_ACCESS_TOKEN to nx-cloud.env
    #   shell: bash
    #   run: echo "NX_CLOUD_ACCESS_TOKEN=${{ inputs.NX_CLOUD_ACCESS_TOKEN }}" >> nx-cloud.env
