name: Install Dependencies
description: Use node and install the project dependencies

runs:
  using: 'composite'
  steps:
    - name: ⎔ Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'yarn'
    - name: 📥 Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
    - name: Generate prisma types
      shell: bash
      run: yarn run prisma:generate
