import './tailwind.css';
import { GlobalProviders } from './GlobalProviders';
import {
  Alegreya_Sans_SC,
  Alegreya_Sans,
  Alegreya,
  Source_Code_Pro,
} from 'next/font/google';
import { Metadata } from 'next';

const alegreyaSansSC = Alegreya_Sans_SC({
  weight: ['500', '800'],
  subsets: ['latin'],
  variable: '--typeface-alegreya-sans-sc',
});

const alegreyaSans = Alegreya_Sans({
  weight: ['100', '400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--typeface-alegreya-sans',
});

const alegreya = Alegreya({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--typeface-alegreya',
});

const sourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
  variable: '--typeface-source-code-pro',
});

export const metadata: Metadata = {
  title: 'Anish George',
  description: 'Generated by create-nx-workspace',
  icons: [
    { rel: 'icon', url: '/favicon.ico' },
    { rel: 'apple-touch-icon', url: '/apple-touch-icon.png' },
  ],
  manifest: '/site.webmanifest',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`dark ${alegreyaSansSC.variable} ${alegreyaSans.variable} ${alegreya.variable} ${sourceCodePro.variable}`}
    >
      <body>
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  );
}
