import Head from 'next/head';
import './tailwind.css';
import { GlobalProviders } from './GlobalProviders';
import {
  Alegreya_Sans_SC,
  Alegreya_Sans,
  Alegreya,
  Source_Code_Pro,
} from 'next/font/google';

const alegreyaSansSC = Alegreya_Sans_SC({
  weight: ['500', '800'],
  subsets: ['latin'],
  variable: '--typeface-alegreya-sans-sc',
});

const alegreyaSans = Alegreya_Sans({
  weight: ['100', '400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--typeface-alegreya-sans',
});

const alegreya = Alegreya({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--typeface-alegreya',
});

const sourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
  variable: '--typeface-source-code-pro',
});

export const metadata = {
  title: 'Welcome to ageorgedev',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${alegreyaSansSC.variable} ${alegreyaSans.variable} ${alegreya.variable} ${sourceCodePro.variable}`}
    >
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <body>
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  );
}
