name: 'Planetscale'
description: 'Set up the planetscale cli'
runs:
  using: 'composite'
  steps:
    - name: Install Planetscale CLI
      shell: bash
      env:
        CLI_VERSION: 0.156.0
      run: |
        mkdir -p ~/pscale-install
        wget -P ~/pscale-install https://github.com/planetscale/cli/releases/download/v${CLI_VERSION}/pscale_${CLI_VERSION}_linux_amd64.deb
        sudo dpkg -i ~/pscale-install/pscale_${CLI_VERSION}_linux_amd64.deb
        sudo apt-get install -f
        pscale version
        rm -rf ~/pscale-install
