name: 'Planetscale'
description: 'Create a branch in a Planetscale database'
inputs:
  db_branch_name:
    required: true
    description: Name of the branch
  actions:
    required: true
    description: Actions to perform. Comma separated list of actions. Valid actions - create, delete, deploy-request
    default: 'create'
  DB_NAME:
    required: true
    description: Database name
  ORG_NAME:
    required: true
    description: Organisation
  PLANETSCALE_SERVICE_TOKEN:
    required: true
    description: Service token
  PLANETSCALE_SERVICE_TOKEN_ID:
    required: true
    description: Service token id

outputs:
  db_branch_url:
    description: 'URL of the db branch'
    value: ${{ steps.createBranch.outputs.DB_BRANCH_URL }}
  DB_BRANCH_CONNECTION_STRING:
    description: 'Connection string for the db_branch'
    value: ${{ steps.createBranch.outputs.DB_BRANCH_CONNECTION_STRING }}

runs:
  using: 'composite'
  steps:
    - name: Install Planetscale CLI
      shell: bash
      env:
        CLI_VERSION: 0.139.0
      run: |
        mkdir -p ~/pscale-install
        wget -P ~/pscale-install https://github.com/planetscale/cli/releases/download/v${CLI_VERSION}/pscale_${CLI_VERSION}_linux_amd64.deb
        sudo dpkg -i ~/pscale-install/pscale_${CLI_VERSION}_linux_amd64.deb
        sudo apt-get install -f
        pscale version
        rm -rf ~/pscale-install
    - name: Test connection
      env:
        DB_NAME: ${{ inputs.DB_NAME }}
        ORG_NAME: ${{ inputs.ORG_NAME }}
        PLANETSCALE_SERVICE_TOKEN: ${{ inputs.PLANETSCALE_SERVICE_TOKEN }}
        PLANETSCALE_SERVICE_TOKEN_ID: ${{ inputs.PLANETSCALE_SERVICE_TOKEN_ID }}
      run: pscale branch list $DB_NAME --org $ORG_NAME
      shell: bash
    - name: Create branch
      id: createBranch
      shell: bash
      if: contains(inputs.actions, 'create')
      env:
        DB_NAME: ${{ inputs.DB_NAME }}
        ORG_NAME: ${{ inputs.ORG_NAME }}
        PLANETSCALE_SERVICE_TOKEN: ${{ inputs.PLANETSCALE_SERVICE_TOKEN }}
        PLANETSCALE_SERVICE_TOKEN_ID: ${{ inputs.PLANETSCALE_SERVICE_TOKEN_ID }}
        DB_BRANCH_NAME: ${{ inputs.db_branch_name }}
      run: |
        cd scripts/pscale
        bash create-branch.sh $DB_BRANCH_NAME
