// Reads spells-2024.csv and emits spells-2024.generated.ts.
// Run via: yarn generate:spells
// Run via: yarn generate:spells:check  (exits non-zero if generated file is out of sync)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'csv-parse/sync';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CHECK_MODE = process.argv.includes('--check');

const VALID_SCHOOLS = new Set([
  'Abjuration',
  'Conjuration',
  'Divination',
  'Enchantment',
  'Evocation',
  'Illusion',
  'Necromancy',
  'Transmutation',
]);

interface CsvRow {
  name: string;
  url: string;
  level: string;
  school: string;
  castingTime: string;
  range: string;
  duration: string;
  verbal: string;
  somatic: string;
  material: string;
  concentration: string;
  ritual: string;
  source: string;
}

function toPascalCase(name: string): string {
  return name
    .replace(/'/g, '')
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

function parseBool(val: string): boolean {
  return val.trim().toLowerCase() === 'true';
}

function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

const csvPath = join(__dirname, '../src/lib/data/spells-2024.csv');
const outPath = join(__dirname, '../src/lib/data/spells-2024.generated.ts');

const csvContent = readFileSync(csvPath, 'utf-8');
const rows: CsvRow[] = parse(csvContent, {
  columns: true,
  skip_empty_lines: true,
});

const errors: string[] = [];
const keyMap = new Map<string, string>();
const entries: string[] = [];

for (const row of rows) {
  if (!VALID_SCHOOLS.has(row.school)) {
    errors.push(`Unknown school '${row.school}' for spell '${row.name}'`);
    continue;
  }

  const key = toPascalCase(row.name);

  if (keyMap.has(key)) {
    errors.push(
      `Key collision: '${key}' produced by both '${keyMap.get(key)}' and '${row.name}'`
    );
    continue;
  }
  keyMap.set(key, row.name);

  const verbal = parseBool(row.verbal);
  const somatic = parseBool(row.somatic);
  const material = parseBool(row.material);
  const concentration = parseBool(row.concentration);
  const ritual = parseBool(row.ritual);

  const componentsFields = [
    verbal ? `verbal: true` : `verbal: false`,
    somatic ? `somatic: true` : `somatic: false`,
    material ? `material: true` : `material: false`,
  ].join(', ');

  entries.push(
    `  ${key}: {
    name: '${escapeString(row.name)}',
    url: '${escapeString(row.url)}',
    level: ${parseInt(row.level, 10)},
    school: '${row.school}',
    castingTime: '${escapeString(row.castingTime)}',
    range: '${escapeString(row.range)}',
    duration: '${escapeString(row.duration)}',
    components: { ${componentsFields} },
    concentration: ${concentration},
    ritual: ${ritual},
  }`
  );
}

if (errors.length > 0) {
  for (const err of errors) {
    process.stderr.write(`ERROR: ${err}\n`);
  }
  process.exit(1);
}

const output = `// AUTO-GENERATED by scripts/generate-spells.ts — do not edit manually.
// Run \`yarn generate:spells\` after editing spells-2024.csv.
import type { Spell } from '../models/spellcasting.js';

export const SPELL = {
${entries.join(',\n')}
} as const satisfies Record<string, Spell>;
`;

if (CHECK_MODE) {
  let committed: string;
  try {
    committed = readFileSync(outPath, 'utf-8');
  } catch {
    process.stderr.write(
      `ERROR: Generated file not found at ${outPath}. Run yarn generate:spells first.\n`
    );
    process.exit(1);
  }

  if (committed !== output) {
    process.stderr.write(
      `DRIFT DETECTED: spells-2024.generated.ts is out of sync with spells-2024.csv.\nRun \`yarn generate:spells\` and commit the result.\n`
    );
    process.exit(1);
  }

  process.stdout.write(`✓ spells-2024.generated.ts is in sync with the CSV.\n`);
} else {
  writeFileSync(outPath, output, 'utf-8');
  process.stdout.write(`Generated ${entries.length} spells → ${outPath}\n`);
}
