/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as NoLayoutResumeRouteImport } from './routes/_noLayout/resume'
import { Route as NoLayoutCharTestRouteImport } from './routes/_noLayout/char-test'
import { Route as PublicTalksIndexRouteImport } from './routes/_public/talks.index'
import { Route as PublicTalksTailwindRouteImport } from './routes/_public/talks.tailwind'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const NoLayoutResumeRoute = NoLayoutResumeRouteImport.update({
  id: '/_noLayout/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const NoLayoutCharTestRoute = NoLayoutCharTestRouteImport.update({
  id: '/_noLayout/char-test',
  path: '/char-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTalksIndexRoute = PublicTalksIndexRouteImport.update({
  id: '/talks/',
  path: '/talks/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTalksTailwindRoute = PublicTalksTailwindRouteImport.update({
  id: '/talks/tailwind',
  path: '/talks/tailwind',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/char-test': typeof NoLayoutCharTestRoute
  '/resume': typeof NoLayoutResumeRoute
  '/talks/tailwind': typeof PublicTalksTailwindRoute
  '/talks/': typeof PublicTalksIndexRoute
}
export interface FileRoutesByTo {
  '/char-test': typeof NoLayoutCharTestRoute
  '/resume': typeof NoLayoutResumeRoute
  '/': typeof PublicIndexRoute
  '/talks/tailwind': typeof PublicTalksTailwindRoute
  '/talks': typeof PublicTalksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_noLayout/char-test': typeof NoLayoutCharTestRoute
  '/_noLayout/resume': typeof NoLayoutResumeRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/talks/tailwind': typeof PublicTalksTailwindRoute
  '/_public/talks/': typeof PublicTalksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/char-test' | '/resume' | '/talks/tailwind' | '/talks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/char-test' | '/resume' | '/' | '/talks/tailwind' | '/talks'
  id:
    | '__root__'
    | '/_public'
    | '/_noLayout/char-test'
    | '/_noLayout/resume'
    | '/_public/'
    | '/_public/talks/tailwind'
    | '/_public/talks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  NoLayoutCharTestRoute: typeof NoLayoutCharTestRoute
  NoLayoutResumeRoute: typeof NoLayoutResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_noLayout/resume': {
      id: '/_noLayout/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof NoLayoutResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_noLayout/char-test': {
      id: '/_noLayout/char-test'
      path: '/char-test'
      fullPath: '/char-test'
      preLoaderRoute: typeof NoLayoutCharTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/talks/': {
      id: '/_public/talks/'
      path: '/talks'
      fullPath: '/talks/'
      preLoaderRoute: typeof PublicTalksIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/talks/tailwind': {
      id: '/_public/talks/tailwind'
      path: '/talks/tailwind'
      fullPath: '/talks/tailwind'
      preLoaderRoute: typeof PublicTalksTailwindRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicTalksTailwindRoute: typeof PublicTalksTailwindRoute
  PublicTalksIndexRoute: typeof PublicTalksIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicTalksTailwindRoute: PublicTalksTailwindRoute,
  PublicTalksIndexRoute: PublicTalksIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  NoLayoutCharTestRoute: NoLayoutCharTestRoute,
  NoLayoutResumeRoute: NoLayoutResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
