name: Promote vercel site to production
description: Deploy an app to Vercel
inputs:
  VERCEL_ACCESS_TOKEN:
    required: true
    description: 'Token for Vercel authentication'
  deploy_url:
    required: true
    description: 'Vercel url to promote'
  VERCEL_PROJECT_NAME:
    required: true
    description: 'Vercel project name'

runs:
  using: 'composite'
  steps:
    - name: Setup vercel
      uses: ./.github/actions/setup-vercel-cli
      with:
        VERCEL_ACCESS_TOKEN: ${{ inputs.VERCEL_ACCESS_TOKEN }}
        VERCEL_PROJECT_NAME: ${{ inputs.VERCEL_PROJECT_NAME }}
    - name: Promote app to production
      shell: bash
      env:
        VERCEL_ACCESS_TOKEN: ${{ inputs.VERCEL_ACCESS_TOKEN }}
      run: |
        vercel promote ${{ inputs.deploy_url }} --scope anish-georges-projects --token $VERCEL_ACCESS_TOKEN
