name: Setup vercel CLI
description: Install vercel CLI and connect project
inputs:
  VERCEL_ACCESS_TOKEN:
    required: true
    description: 'Token for Vercel authentication'
  VERCEL_PROJECT_NAME:
    required: true
    description: 'Vercel project name'

runs:
  using: 'composite'
  steps:
    - name: Install vercel CLI if not available
      shell: bash
      run: |
        if ! command -v vercel &> /dev/null
        then
            echo "vercel command could not be found, installing..."
            npm install -g vercel
        fi
    - name: Link vercel project
      shell: bash
      env:
        VERCEL_ACCESS_TOKEN: ${{ inputs.VERCEL_ACCESS_TOKEN }}
      run: |
        vercel link --project ${{ inputs.VERCEL_PROJECT_NAME }} --yes --token $VERCEL_ACCESS_TOKEN
