name: Deploy Site
description: Deploy ageorgedev app to Netlify
inputs:
  production:
    required: false
    description: 'Whether to deploy the production site or do a branch deploy, true/false'
    default: 'false'
  note:
    required: true
    description: 'Added note for deploy context'
  NETLIFY_SITE_ID:
    required: true
    description: 'Site ID at netlify'
  NETLIFY_AUTH_TOKEN:
    required: true
    description: 'Token for Netlify authentication'
outputs:
  preview_url:
    description: 'Preview Url deployed to if any'
    value: ${{ steps.deployInfo.outputs.PREVIEW_URL }}
  logs_url:
    description: 'Logs Url'
    value: ${{ steps.deployInfo.outputs.LOGS_URL }}

runs:
  using: 'composite'
  steps:
    - name: 🏗️ Build and 🚀 Deploy
      shell: bash
      working-directory: apps/ageorgedev
      env:
        NETLIFY_SITE_ID: ${{ inputs.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
      run: |
        echo "Building and deploying..."
        set -o pipefail
        yarn netlify deploy --build ${{ fromJSON('{"true": "--prod --context production", "false": "--context branch-deploy --alias preview"}')[inputs.production] }} --message "${{ inputs.note }}" 2>&1 | tee deploy-output.txt
        set +o pipefail
    - name: ⎔ Extract deployment information
      shell: bash
      id: deployInfo
      working-directory: apps/ageorgedev
      run: |
        echo "Extracting deployment information..."
        echo "PREVIEW_URL=$(cat deploy-output.txt | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*(--)[a-zA-Z0-9./?=_-]*')" >> $GITHUB_OUTPUT
        echo "LOGS_URL=$(cat deploy-output.txt | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*')" >> $GITHUB_OUTPUT
