name: Run e2e
description: Run cypress e2e tests against site url
inputs:
  site_url:
    required: true
    description: 'Site url to run e2e tests against'
  project:
    required: true
    description: 'nx project which runs the e2e'

runs:
  using: 'composite'
  steps:
    - name: ⚡ Run cypress against deployed application
      shell: bash
      env:
        SITE_URL: ${{ inputs.site_url }}
      run: yarn nx e2e ${{ inputs.project }} --baseUrl=$SITE_URL
