/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicDndCharactersIndexRouteImport } from './routes/_public/dnd/characters/index'
import { Route as PublicDndCharactersExampleRouteImport } from './routes/_public/dnd/characters/example'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDndCharactersIndexRoute =
  PublicDndCharactersIndexRouteImport.update({
    id: '/dnd/characters/',
    path: '/dnd/characters/',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicDndCharactersExampleRoute =
  PublicDndCharactersExampleRouteImport.update({
    id: '/dnd/characters/example',
    path: '/dnd/characters/example',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dnd/characters/example': typeof PublicDndCharactersExampleRoute
  '/dnd/characters/': typeof PublicDndCharactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dnd/characters/example': typeof PublicDndCharactersExampleRoute
  '/dnd/characters': typeof PublicDndCharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_public/dnd/characters/example': typeof PublicDndCharactersExampleRoute
  '/_public/dnd/characters/': typeof PublicDndCharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dnd/characters/example' | '/dnd/characters/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dnd/characters/example' | '/dnd/characters'
  id:
    | '__root__'
    | '/_public'
    | '/_public/'
    | '/_public/dnd/characters/example'
    | '/_public/dnd/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dnd/characters/': {
      id: '/_public/dnd/characters/'
      path: '/dnd/characters'
      fullPath: '/dnd/characters/'
      preLoaderRoute: typeof PublicDndCharactersIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dnd/characters/example': {
      id: '/_public/dnd/characters/example'
      path: '/dnd/characters/example'
      fullPath: '/dnd/characters/example'
      preLoaderRoute: typeof PublicDndCharactersExampleRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDndCharactersExampleRoute: typeof PublicDndCharactersExampleRoute
  PublicDndCharactersIndexRoute: typeof PublicDndCharactersIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicDndCharactersExampleRoute: PublicDndCharactersExampleRoute,
  PublicDndCharactersIndexRoute: PublicDndCharactersIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
