/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicDndCharactersIndexRouteImport } from './routes/_public/dnd/characters/index'
import { Route as PublicDndCharactersSheetRouteImport } from './routes/_public/dnd/characters/_sheet'
import { Route as PublicDndCharactersSheetSaoraEmbervaleRouteImport } from './routes/_public/dnd/characters/_sheet/saora-embervale'
import { Route as PublicDndCharactersSheetOmarinKenateRouteImport } from './routes/_public/dnd/characters/_sheet/omarin-kenate'
import { Route as PublicDndCharactersSheetGonvarFeathertideRouteImport } from './routes/_public/dnd/characters/_sheet/gonvar-feathertide'
import { Route as PublicDndCharactersSheetClawRouteImport } from './routes/_public/dnd/characters/_sheet/claw'
import { Route as PublicDndCharactersSheetZoynari3RouteImport } from './routes/_public/dnd/characters/_sheet/zoynari.3'
import { Route as PublicDndCharactersSheetZoynari2RouteImport } from './routes/_public/dnd/characters/_sheet/zoynari.2'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDndCharactersIndexRoute =
  PublicDndCharactersIndexRouteImport.update({
    id: '/dnd/characters/',
    path: '/dnd/characters/',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicDndCharactersSheetRoute =
  PublicDndCharactersSheetRouteImport.update({
    id: '/dnd/characters/_sheet',
    path: '/dnd/characters',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicDndCharactersSheetSaoraEmbervaleRoute =
  PublicDndCharactersSheetSaoraEmbervaleRouteImport.update({
    id: '/saora-embervale',
    path: '/saora-embervale',
    getParentRoute: () => PublicDndCharactersSheetRoute,
  } as any)
const PublicDndCharactersSheetOmarinKenateRoute =
  PublicDndCharactersSheetOmarinKenateRouteImport.update({
    id: '/omarin-kenate',
    path: '/omarin-kenate',
    getParentRoute: () => PublicDndCharactersSheetRoute,
  } as any)
const PublicDndCharactersSheetGonvarFeathertideRoute =
  PublicDndCharactersSheetGonvarFeathertideRouteImport.update({
    id: '/gonvar-feathertide',
    path: '/gonvar-feathertide',
    getParentRoute: () => PublicDndCharactersSheetRoute,
  } as any)
const PublicDndCharactersSheetClawRoute =
  PublicDndCharactersSheetClawRouteImport.update({
    id: '/claw',
    path: '/claw',
    getParentRoute: () => PublicDndCharactersSheetRoute,
  } as any)
const PublicDndCharactersSheetZoynari3Route =
  PublicDndCharactersSheetZoynari3RouteImport.update({
    id: '/zoynari/3',
    path: '/zoynari/3',
    getParentRoute: () => PublicDndCharactersSheetRoute,
  } as any)
const PublicDndCharactersSheetZoynari2Route =
  PublicDndCharactersSheetZoynari2RouteImport.update({
    id: '/zoynari/2',
    path: '/zoynari/2',
    getParentRoute: () => PublicDndCharactersSheetRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dnd/characters': typeof PublicDndCharactersSheetRouteWithChildren
  '/dnd/characters/': typeof PublicDndCharactersIndexRoute
  '/dnd/characters/claw': typeof PublicDndCharactersSheetClawRoute
  '/dnd/characters/gonvar-feathertide': typeof PublicDndCharactersSheetGonvarFeathertideRoute
  '/dnd/characters/omarin-kenate': typeof PublicDndCharactersSheetOmarinKenateRoute
  '/dnd/characters/saora-embervale': typeof PublicDndCharactersSheetSaoraEmbervaleRoute
  '/dnd/characters/zoynari/2': typeof PublicDndCharactersSheetZoynari2Route
  '/dnd/characters/zoynari/3': typeof PublicDndCharactersSheetZoynari3Route
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dnd/characters': typeof PublicDndCharactersIndexRoute
  '/dnd/characters/claw': typeof PublicDndCharactersSheetClawRoute
  '/dnd/characters/gonvar-feathertide': typeof PublicDndCharactersSheetGonvarFeathertideRoute
  '/dnd/characters/omarin-kenate': typeof PublicDndCharactersSheetOmarinKenateRoute
  '/dnd/characters/saora-embervale': typeof PublicDndCharactersSheetSaoraEmbervaleRoute
  '/dnd/characters/zoynari/2': typeof PublicDndCharactersSheetZoynari2Route
  '/dnd/characters/zoynari/3': typeof PublicDndCharactersSheetZoynari3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_public/dnd/characters/_sheet': typeof PublicDndCharactersSheetRouteWithChildren
  '/_public/dnd/characters/': typeof PublicDndCharactersIndexRoute
  '/_public/dnd/characters/_sheet/claw': typeof PublicDndCharactersSheetClawRoute
  '/_public/dnd/characters/_sheet/gonvar-feathertide': typeof PublicDndCharactersSheetGonvarFeathertideRoute
  '/_public/dnd/characters/_sheet/omarin-kenate': typeof PublicDndCharactersSheetOmarinKenateRoute
  '/_public/dnd/characters/_sheet/saora-embervale': typeof PublicDndCharactersSheetSaoraEmbervaleRoute
  '/_public/dnd/characters/_sheet/zoynari/2': typeof PublicDndCharactersSheetZoynari2Route
  '/_public/dnd/characters/_sheet/zoynari/3': typeof PublicDndCharactersSheetZoynari3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dnd/characters'
    | '/dnd/characters/'
    | '/dnd/characters/claw'
    | '/dnd/characters/gonvar-feathertide'
    | '/dnd/characters/omarin-kenate'
    | '/dnd/characters/saora-embervale'
    | '/dnd/characters/zoynari/2'
    | '/dnd/characters/zoynari/3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dnd/characters'
    | '/dnd/characters/claw'
    | '/dnd/characters/gonvar-feathertide'
    | '/dnd/characters/omarin-kenate'
    | '/dnd/characters/saora-embervale'
    | '/dnd/characters/zoynari/2'
    | '/dnd/characters/zoynari/3'
  id:
    | '__root__'
    | '/_public'
    | '/_public/'
    | '/_public/dnd/characters/_sheet'
    | '/_public/dnd/characters/'
    | '/_public/dnd/characters/_sheet/claw'
    | '/_public/dnd/characters/_sheet/gonvar-feathertide'
    | '/_public/dnd/characters/_sheet/omarin-kenate'
    | '/_public/dnd/characters/_sheet/saora-embervale'
    | '/_public/dnd/characters/_sheet/zoynari/2'
    | '/_public/dnd/characters/_sheet/zoynari/3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dnd/characters/': {
      id: '/_public/dnd/characters/'
      path: '/dnd/characters'
      fullPath: '/dnd/characters/'
      preLoaderRoute: typeof PublicDndCharactersIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dnd/characters/_sheet': {
      id: '/_public/dnd/characters/_sheet'
      path: '/dnd/characters'
      fullPath: '/dnd/characters'
      preLoaderRoute: typeof PublicDndCharactersSheetRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dnd/characters/_sheet/saora-embervale': {
      id: '/_public/dnd/characters/_sheet/saora-embervale'
      path: '/saora-embervale'
      fullPath: '/dnd/characters/saora-embervale'
      preLoaderRoute: typeof PublicDndCharactersSheetSaoraEmbervaleRouteImport
      parentRoute: typeof PublicDndCharactersSheetRoute
    }
    '/_public/dnd/characters/_sheet/omarin-kenate': {
      id: '/_public/dnd/characters/_sheet/omarin-kenate'
      path: '/omarin-kenate'
      fullPath: '/dnd/characters/omarin-kenate'
      preLoaderRoute: typeof PublicDndCharactersSheetOmarinKenateRouteImport
      parentRoute: typeof PublicDndCharactersSheetRoute
    }
    '/_public/dnd/characters/_sheet/gonvar-feathertide': {
      id: '/_public/dnd/characters/_sheet/gonvar-feathertide'
      path: '/gonvar-feathertide'
      fullPath: '/dnd/characters/gonvar-feathertide'
      preLoaderRoute: typeof PublicDndCharactersSheetGonvarFeathertideRouteImport
      parentRoute: typeof PublicDndCharactersSheetRoute
    }
    '/_public/dnd/characters/_sheet/claw': {
      id: '/_public/dnd/characters/_sheet/claw'
      path: '/claw'
      fullPath: '/dnd/characters/claw'
      preLoaderRoute: typeof PublicDndCharactersSheetClawRouteImport
      parentRoute: typeof PublicDndCharactersSheetRoute
    }
    '/_public/dnd/characters/_sheet/zoynari/3': {
      id: '/_public/dnd/characters/_sheet/zoynari/3'
      path: '/zoynari/3'
      fullPath: '/dnd/characters/zoynari/3'
      preLoaderRoute: typeof PublicDndCharactersSheetZoynari3RouteImport
      parentRoute: typeof PublicDndCharactersSheetRoute
    }
    '/_public/dnd/characters/_sheet/zoynari/2': {
      id: '/_public/dnd/characters/_sheet/zoynari/2'
      path: '/zoynari/2'
      fullPath: '/dnd/characters/zoynari/2'
      preLoaderRoute: typeof PublicDndCharactersSheetZoynari2RouteImport
      parentRoute: typeof PublicDndCharactersSheetRoute
    }
  }
}

interface PublicDndCharactersSheetRouteChildren {
  PublicDndCharactersSheetClawRoute: typeof PublicDndCharactersSheetClawRoute
  PublicDndCharactersSheetGonvarFeathertideRoute: typeof PublicDndCharactersSheetGonvarFeathertideRoute
  PublicDndCharactersSheetOmarinKenateRoute: typeof PublicDndCharactersSheetOmarinKenateRoute
  PublicDndCharactersSheetSaoraEmbervaleRoute: typeof PublicDndCharactersSheetSaoraEmbervaleRoute
  PublicDndCharactersSheetZoynari2Route: typeof PublicDndCharactersSheetZoynari2Route
  PublicDndCharactersSheetZoynari3Route: typeof PublicDndCharactersSheetZoynari3Route
}

const PublicDndCharactersSheetRouteChildren: PublicDndCharactersSheetRouteChildren =
  {
    PublicDndCharactersSheetClawRoute: PublicDndCharactersSheetClawRoute,
    PublicDndCharactersSheetGonvarFeathertideRoute:
      PublicDndCharactersSheetGonvarFeathertideRoute,
    PublicDndCharactersSheetOmarinKenateRoute:
      PublicDndCharactersSheetOmarinKenateRoute,
    PublicDndCharactersSheetSaoraEmbervaleRoute:
      PublicDndCharactersSheetSaoraEmbervaleRoute,
    PublicDndCharactersSheetZoynari2Route:
      PublicDndCharactersSheetZoynari2Route,
    PublicDndCharactersSheetZoynari3Route:
      PublicDndCharactersSheetZoynari3Route,
  }

const PublicDndCharactersSheetRouteWithChildren =
  PublicDndCharactersSheetRoute._addFileChildren(
    PublicDndCharactersSheetRouteChildren,
  )

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDndCharactersSheetRoute: typeof PublicDndCharactersSheetRouteWithChildren
  PublicDndCharactersIndexRoute: typeof PublicDndCharactersIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicDndCharactersSheetRoute: PublicDndCharactersSheetRouteWithChildren,
  PublicDndCharactersIndexRoute: PublicDndCharactersIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
