/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoLayoutDndCharactersExampleRouteImport } from './routes/_noLayout/dnd/characters/example'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoLayoutDndCharactersExampleRoute =
  NoLayoutDndCharactersExampleRouteImport.update({
    id: '/_noLayout/dnd/characters/example',
    path: '/dnd/characters/example',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dnd/characters/example': typeof NoLayoutDndCharactersExampleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dnd/characters/example': typeof NoLayoutDndCharactersExampleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_noLayout/dnd/characters/example': typeof NoLayoutDndCharactersExampleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dnd/characters/example'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dnd/characters/example'
  id: '__root__' | '/' | '/_noLayout/dnd/characters/example'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoLayoutDndCharactersExampleRoute: typeof NoLayoutDndCharactersExampleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_noLayout/dnd/characters/example': {
      id: '/_noLayout/dnd/characters/example'
      path: '/dnd/characters/example'
      fullPath: '/dnd/characters/example'
      preLoaderRoute: typeof NoLayoutDndCharactersExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoLayoutDndCharactersExampleRoute: NoLayoutDndCharactersExampleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
