name: Deploy Vercel site
description: Deploy an app to Vercel
inputs:
  production:
    required: false
    default: 'false'
    description: 'Whether to deploy the production site or do a preview deploy, true/false'
  staged:
    required: false
    default: 'false'
    description: 'Weather to stop the auto link of domain to the deployment'
  VERCEL_ACCESS_TOKEN:
    required: true
    description: 'Token for Vercel authentication'
  VERCEL_PROJECT_NAME:
    required: true
    description: 'Vercel project name'
outputs:
  deploy_url:
    description: 'URL of deployed site'
    value: ${{ steps.deployInfo.outputs.DEPLOY_URL }}

runs:
  using: 'composite'
  steps:
    - name: Setup vercel
      uses: ./.github/actions/setup-vercel-cli
      with:
        VERCEL_ACCESS_TOKEN: ${{ inputs.VERCEL_ACCESS_TOKEN }}
        VERCEL_PROJECT_NAME: ${{ inputs.VERCEL_PROJECT_NAME }}
    - name: ðŸ—ï¸ Build project, pulling environment
      shell: bash
      env:
        VERCEL_ACCESS_TOKEN: ${{ inputs.VERCEL_ACCESS_TOKEN }}
      run: |
        vercel build ${{ fromJSON('{ "true": "--prod", "false": "" }')[inputs.production] }} --yes --token $VERCEL_ACCESS_TOKEN
    - name: ðŸš€ Deploy
      shell: bash
      env:
        VERCEL_ACCESS_TOKEN: ${{ inputs.VERCEL_ACCESS_TOKEN }}
      run: |
        vercel deploy ${{ fromJSON('{ "true": { "true": "--prod --skip-domain", "false": "--prod" }, "false": { "true": "", "false": "" } }')[inputs.production][inputs.staged] }} --prebuilt --token $VERCEL_ACCESS_TOKEN > deploy-url.txt
    - name: âŽ” Extract deployment information
      shell: bash
      id: deployInfo
      run: |
        echo "DEPLOY_URL=$(cat deploy-url.txt)" >> $GITHUB_OUTPUT
