[build]
  command = "cd ../../; yarn nx build ageorgedev"
  publish = "public"
  ignore = "yarn should-ignore-build"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
