name: Deploy a.george.dev site
on:
  workflow_call:
    inputs:
      VERCEL_PROJECT_NAME:
        required: true
        type: string
      production:
        required: true
        type: boolean
      e2e_project:
        required: false
        type: string
    secrets:
      VERCEL_ACCESS_TOKEN:
        required: true
      NX_CLOUD_ACCESS_TOKEN:
        required: true
    outputs:
      deploy_url:
        description: 'URL of the deployed site'
        value: ${{ jobs.Deploy.outputs.deploy_url }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repository code
        uses: actions/checkout@v4
      - name: 📦 Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: 🚀 Deploy site
        uses: ./.github/actions/deploy-to-vercel
        id: deploy
        with:
          production: ${{ inputs.production }}
          staged: true
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_PROJECT_NAME: ${{ inputs.VERCEL_PROJECT_NAME }}
      - name: 🧪 Run e2e
        if: ${{ inputs.e2e_project }}
        uses: ./.github/actions/run-e2e
        with:
          site_url: ${{ steps.deploy.outputs.deploy_url }}
          project: ${{ inputs.e2e_project }}
      - name: Promote to production
        if: ${{ inputs.production }}
        uses: ./.github/actions/promote-vercel-app
        with:
          deploy_url: ${{ steps.deploy.outputs.deploy_url }}
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_PROJECT_NAME: ${{ inputs.VERCEL_PROJECT_NAME }}
    outputs:
      deploy_url: ${{ steps.deploy.outputs.deploy_url }}
