name: Dummy workflow
on:
  workflow_dispatch:
  push:
    branches: [feature/*]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run a random command
        run: yarn nx affected:apps
