name: Dummy workflow
on:
  workflow_dispatch:

jobs:
  Setup_DB:
    uses: ./.github/workflows/setup-db.yml
    with:
      DB_BRANCH_NAME: ${{ vars.DB_BRANCH_NAME }}
      should_deploy_schema: ${{ false }}
    secrets:
      PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      DB_NAME: ${{ secrets.DB_NAME }}
      ORG_NAME: ${{ secrets.ORG_NAME }}
  Site_Preview:
    needs: [Setup_DB]
    uses: ./.github/workflows/site-preview.yml
    with:
      title: ${{ format('Pull request {0} - {1}', github.event.pull_request.number, github.event.pull_request.title) }}
      NETLIFY_SITE_ID: ${{ vars.AGEORGEDEV_SITE_ID }}
      DB_BRANCH_NAME: ${{ vars.DB_BRANCH_NAME }}
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      DB_NAME: ${{ secrets.DB_NAME }}
      ORG_NAME: ${{ secrets.ORG_NAME }}
