name: Dummy workflow
on:
  workflow_dispatch:
  push:
    branches: [feature/*]

jobs:
  Info:
    uses: ./.github/workflows/info.yml
  Setup_DB:
    needs: [Info]
    uses: ./.github/workflows/setup-db.yml
    with:
      DB_BRANCH_NAME: ${{ vars.DB_BRANCH_NAME_ALT }}
      should_deploy_schema: ${{ needs.Info.outputs.should_deploy_schema == 'true' }}
    secrets:
      PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      DB_NAME: ${{ secrets.DB_NAME }}
      ORG_NAME: ${{ secrets.ORG_NAME }}
  Checks:
    needs: [Setup_DB]
    runs-on: ubuntu-latest
    steps:
      - name: Yes, need to create DR
        if: needs.Setup_DB.outputs.should_create_dr == 'true'
        run: echo "Create DR"
      - name: No, don't need to create DR
        if: needs.Setup_DB.outputs.should_create_dr == 'false'
        run: echo "Don't create DR"
