name: Dummy workflow
on:
  workflow_dispatch:

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repository code
        uses: actions/checkout@v3
      - name: Information
        run: echo "This is a dummy workflow used to test out stuff"
