name: Production
on:
  push:
    branches: [main]

jobs:
  Info:
    uses: ./.github/workflows/info.yml
  Run_Tests:
    needs: [Info]
    uses: ./.github/workflows/tests.yml
  Deploy:
    needs: [Run_Tests, Info]
    strategy:
      matrix:
        project: ${{ fromJSON(needs.Info.outputs.production_deploy_matrix) }}
    uses: ./.github/workflows/deploy-vercel-project.yml
    with:
      VERCEL_PROJECT_NAME: ${{ matrix.project.vercel_project_name }}
      production: true
      e2e_project: ${{ matrix.project.e2e_project || '' }}
    secrets:
      VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
