name: PR workflow
on:
  pull_request:
    branches: [main]

jobs:
  Info:
    uses: ./.github/workflows/info.yml
  Run_Tests:
    needs: [Info]
    uses: ./.github/workflows/tests.yml
    with:
      command_arg: --affected
  Deploy:
    needs: [Run_Tests, Info]
    if: needs.Info.outputs.pr_deploy_matrix != '[]'
    permissions:
      pull-requests: write
    strategy:
      matrix:
        project: ${{ fromJSON(needs.Info.outputs.pr_deploy_matrix) }}
    uses: ./.github/workflows/deploy-vercel-project.yml
    with:
      VERCEL_PROJECT_NAME: ${{ matrix.project.vercel_project_name }}
      production: false
      e2e_project: ${{ matrix.project.e2e_project || '' }}
      pull_request_number: ${{ github.event.pull_request.number }}
    secrets:
      VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
