name: 🧪 Tests
on:
  workflow_call:
    inputs:
      command_arg:
        required: false
        type: string
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repository code
        uses: actions/checkout@v6
      - name: 📦 Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: ⚡ Run Unit Tests for given projects
        run: yarn turbo test ${{ inputs.command_arg }} -- --passWithNoTests
