name: 🧪 Tests
on:
  workflow_call:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Turbo
        uses: ./.github/actions/setup-turbo
      - name: 📦 Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: ⚡ Run Unit Tests with coverage
        run: yarn test:coverage
      - name: 📤 Upload coverage lcov
        uses: actions/upload-artifact@v7
        with:
          name: coverage-lcov
          path: coverage/lcov.info
      - name: 🔍 Check spell CSV / generated file are in sync
        run: yarn turbo generate:spells:check --filter=@ageorgedev/dnd-character-sheet
