name: 🧪 Tests
on:
  workflow_call:
    inputs:
      affected_projects:
        required: true
        type: string
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repository code
        uses: actions/checkout@v4
      - name: 📦 Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: ⚡ Run Unit Tests for given projects
        run: echo '${{ inputs.affected_projects }}' | jq -r '.[]' | xargs yarn nx run-many --target=test --passWithNoTests --projects
